name: Release Binaries

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      name: terraform-plan
      steps:
      - uses: hashicorp/setup-terraform@v1

      - run: terraform init

      - id: plan
        run: terraform plan