name: Terraform Plan

on: [push, pull_request]

jobs:
    terraform-plan:
      runs-on: ubuntu-latest
      name: terraform-plan
      steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - id: init
        run: terraform init

      - id: validate
        run: terraform validate

      - id: plan
        run: terraform plan